squad_names = [
    "Альфа",
    "Омега",
    "Феникс",
    "Грифон",
    "Дракон",
    "Волк",
    "Сокол",
    "Титан",
    "Легион",
    "Центурион",
    "Шторм",
    "Север",
    "Молния",
    "Сталь",
    "Кобра",
    "Пантера",
    "Лев",
    "Гладиатор",
    "Викинг",
    "Спартанец",
    "Комета",
    "Буря",
    "Арктика",
    "Торнадо",
    "Ястреб",
    "Медведь",
    "Тигр",
    "Ягуар",
    "Скорпион",
    "Марс",
    "Железо",
    "Рубин",
    "Оникс",
    "Сапфир",
    "Жемчуг",
    "Топаз",
    "Аметист",
    "Опал",
    "Агат",
    "Бриллиант",
    "Небеса",
    "Ореол",
    "Квазар",
    "Нимб",
    "Аврора",
    "Баррикада",
    "Каратель",
    "Навигатор",
    "Пионер",
    "Квант",
    "Эклипс",
    "Галактика",
    "Импульс",
    "Метеор",
    "Нейтрон",
    "Протон",
    "Радар",
    "Сигма",
    "Циклон",
    "СБЭУ",
    "Профессионалов",
    "BEAR",
    "USEC",
    "Скайнет",
    "Скуфов",
    "Решал",
    "LABS",
    "GIGACHADS",
]

[adv]
# Макс кол-во пользователей отображаемых в обьявлении
display_users_limit = 5
# Время до удаления в минутах если канал без лимита на кол-во пользователей
delete_after_unlimit = 3.0
# Время до удаления в минутах если канал заполнен
delete_after_fillment = 4.0
# Время до авто публикации обьявления в минутах
before_auto_pub = 2.0
