services:
  bot:
    image: ghcr.io/folkidevv/partysys:master
    environment:
      - DEBUG=${DEBUG}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DEV_SERVER_ID=${DEV_SERVER_ID}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8081/" ]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
    volumes:
      - /usr/local/src/partysys/bot_partysys:/app/logs
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=caching_sha2_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'partysys'
      MYSQL_USER: 'bot'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /usr/local/src/partysys/db_partysys:/var/lib/mysql