services:
  bot:
    image: ghcr.io/folkidevv/partysys:latest
    command: sh -c "sleep 10s ; python main.py"
    environment:
      - DEBUG=${DEBUG}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DEV_SERVER_ID=${DEV_SERVER_ID}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
    restart: always
    volumes:
      - /usr/local/src/partysys:/app/logs
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=caching_sha2_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'partysys'
      MYSQL_USER: 'bot'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    restart: always
    volumes:
      - /usr/local/src/partysys:/var/lib/mysql